// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"
)

type Wallet struct {
	ID         int64     `db:"id" json:"id"`
	PublicKey  string    `db:"public_key" json:"public_key"`
	PrivateKey string    `db:"private_key" json:"private_key"`
	CreatedAt  time.Time `db:"created_at" json:"created_at"`
}
