// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	CreateWallet(ctx context.Context, arg CreateWalletParams) (Wallet, error)
	GetWallet(ctx context.Context, publicKey string) (Wallet, error)
}

var _ Querier = (*Queries)(nil)
