// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.28.3
// source: airtime.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AirtimeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Network string `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Phone   string `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
}

func (x *AirtimeRequest) Reset() {
	*x = AirtimeRequest{}
	mi := &file_airtime_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AirtimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AirtimeRequest) ProtoMessage() {}

func (x *AirtimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_airtime_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AirtimeRequest.ProtoReflect.Descriptor instead.
func (*AirtimeRequest) Descriptor() ([]byte, []int) {
	return file_airtime_proto_rawDescGZIP(), []int{0}
}

func (x *AirtimeRequest) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *AirtimeRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type AirtimeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *AirtimeResponse) Reset() {
	*x = AirtimeResponse{}
	mi := &file_airtime_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AirtimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AirtimeResponse) ProtoMessage() {}

func (x *AirtimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_airtime_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AirtimeResponse.ProtoReflect.Descriptor instead.
func (*AirtimeResponse) Descriptor() ([]byte, []int) {
	return file_airtime_proto_rawDescGZIP(), []int{1}
}

func (x *AirtimeResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_airtime_proto protoreflect.FileDescriptor

var file_airtime_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x61, 0x69, 0x72, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x02, 0x70, 0x62, 0x22, 0x40, 0x0a, 0x0e, 0x41, 0x69, 0x72, 0x74, 0x69, 0x6d, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x12,
	0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x70, 0x68, 0x6f, 0x6e, 0x65, 0x22, 0x29, 0x0a, 0x0f, 0x41, 0x69, 0x72, 0x74, 0x69, 0x6d, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x42, 0x2e, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x65,
	0x62, 0x75, 0x6b, 0x61, 0x63, 0x6f, 0x64, 0x65, 0x73, 0x32, 0x31, 0x2f, 0x70, 0x65, 0x65, 0x72,
	0x62, 0x69, 0x6c, 0x6c, 0x2d, 0x75, 0x73, 0x65, 0x72, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_airtime_proto_rawDescOnce sync.Once
	file_airtime_proto_rawDescData = file_airtime_proto_rawDesc
)

func file_airtime_proto_rawDescGZIP() []byte {
	file_airtime_proto_rawDescOnce.Do(func() {
		file_airtime_proto_rawDescData = protoimpl.X.CompressGZIP(file_airtime_proto_rawDescData)
	})
	return file_airtime_proto_rawDescData
}

var file_airtime_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_airtime_proto_goTypes = []any{
	(*AirtimeRequest)(nil),  // 0: pb.AirtimeRequest
	(*AirtimeResponse)(nil), // 1: pb.AirtimeResponse
}
var file_airtime_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_airtime_proto_init() }
func file_airtime_proto_init() {
	if File_airtime_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_airtime_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_airtime_proto_goTypes,
		DependencyIndexes: file_airtime_proto_depIdxs,
		MessageInfos:      file_airtime_proto_msgTypes,
	}.Build()
	File_airtime_proto = out.File
	file_airtime_proto_rawDesc = nil
	file_airtime_proto_goTypes = nil
	file_airtime_proto_depIdxs = nil
}
