// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: peerbill_user.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PeerbillUser_GetRates_FullMethodName = "/pb.PeerbillUser/GetRates"
)

// PeerbillUserClient is the client API for PeerbillUser service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PeerbillUserClient interface {
	GetRates(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RateRequest, RateResponse], error)
}

type peerbillUserClient struct {
	cc grpc.ClientConnInterface
}

func NewPeerbillUserClient(cc grpc.ClientConnInterface) PeerbillUserClient {
	return &peerbillUserClient{cc}
}

func (c *peerbillUserClient) GetRates(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RateRequest, RateResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PeerbillUser_ServiceDesc.Streams[0], PeerbillUser_GetRates_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RateRequest, RateResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PeerbillUser_GetRatesClient = grpc.BidiStreamingClient[RateRequest, RateResponse]

// PeerbillUserServer is the server API for PeerbillUser service.
// All implementations must embed UnimplementedPeerbillUserServer
// for forward compatibility.
type PeerbillUserServer interface {
	GetRates(grpc.BidiStreamingServer[RateRequest, RateResponse]) error
	mustEmbedUnimplementedPeerbillUserServer()
}

// UnimplementedPeerbillUserServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPeerbillUserServer struct{}

func (UnimplementedPeerbillUserServer) GetRates(grpc.BidiStreamingServer[RateRequest, RateResponse]) error {
	return status.Errorf(codes.Unimplemented, "method GetRates not implemented")
}
func (UnimplementedPeerbillUserServer) mustEmbedUnimplementedPeerbillUserServer() {}
func (UnimplementedPeerbillUserServer) testEmbeddedByValue()                      {}

// UnsafePeerbillUserServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PeerbillUserServer will
// result in compilation errors.
type UnsafePeerbillUserServer interface {
	mustEmbedUnimplementedPeerbillUserServer()
}

func RegisterPeerbillUserServer(s grpc.ServiceRegistrar, srv PeerbillUserServer) {
	// If the following call pancis, it indicates UnimplementedPeerbillUserServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PeerbillUser_ServiceDesc, srv)
}

func _PeerbillUser_GetRates_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PeerbillUserServer).GetRates(&grpc.GenericServerStream[RateRequest, RateResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PeerbillUser_GetRatesServer = grpc.BidiStreamingServer[RateRequest, RateResponse]

// PeerbillUser_ServiceDesc is the grpc.ServiceDesc for PeerbillUser service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PeerbillUser_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.PeerbillUser",
	HandlerType: (*PeerbillUserServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetRates",
			Handler:       _PeerbillUser_GetRates_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "peerbill_user.proto",
}
